security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider

            json_login:
                check_path: /api/usuarios/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            jwt: ~

    access_control:
        # Rutas públicas (sin autenticación)
        - { path: ^/api/viajes$, roles: PUBLIC_ACCESS, methods: [GET] }               # Listar todos los viajes
        - { path: ^/api/viajes/destacados$, roles: PUBLIC_ACCESS, methods: [GET] }    # Viajes destacados
        - { path: ^/api/actividades$, roles: PUBLIC_ACCESS, methods: [GET] }          # Actividades

        # Rutas de login y creación de usuario públicas
        - { path: ^/api/usuarios/login$, roles: PUBLIC_ACCESS, methods: [POST] }      # Login
        - { path: ^/api/usuarios$, roles: PUBLIC_ACCESS, methods: [POST] }            # Crear usuario

        # Rutas protegidas, es decir, TOKEN necesario
        - { path: ^/api/, roles: ROLE_USER }

    # access_control:
    #     - { path: ^/api, roles: PUBLIC_ACCESS }
        