
version: '3.8'

services:
  react:
    build:
      context: ./tripwme
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - app-network

  symfony:
    build:
      context: ./twm
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://admin:tfgtripwme@symfony-db.c5qwygqc8o89.us-east-1.rds.amazonaws.com:3306/tripwme"
                  # "mysql://admin:tfgtripwme@symfony-db.c5qwygqc8o89.us-east-1.rds.amazonaws.com:3306/tripwme?sslmode=verify-ca&sslrootcert=/etc/ssl/certs/eu-south-2-bundle.pem"
    networks:
      - app-network

  mysql-importer:
    image: mysql:8.0
    depends_on:
      - symfony
    volumes:
      - ./tripwme.sql:/tripwme.sql
    environment:
      MYSQL_PWD: tfgtripwme
    command: >
      sh -c "until mysql -h symfony-db.c5qwygqc8o89.us-east-1.rds.amazonaws.com -u admin -ptfgtripwme -e 'SELECT 1'; do sleep 5; done && mysql -h symfony-db.c5qwygqc8o89.us-east-1.rds.amazonaws.com -u admin -ptfgtripwme -e 'DROP DATABASE IF EXISTS tripwme; CREATE DATABASE tripwme CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;' && mysql -h symfony-db.c5qwygqc8o89.us-east-1.rds.amazonaws.com -u admin -ptfgtripwme tripwme < /tripwme.sql"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge