
version: '3.8'

services:
  react:
    build:
      context: ./tripwme
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

  symfony:
    build:
      context: ./twm
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
